### ISSUE TITLE
condo install - Fabio package does not depend on h5py

### ISSUE THREAD

**Issue by osholm** [silx-kit/fabio#497]
I recently installed a fresh Miniconda3. In this environment I installed fabio using conda:
conda install -c conda-forge fabio

Upon importing fabio I got this message

"ERROR:fabio.nexus:h5py module missing"
which could be fixed by just installing h5py.

I have never build a package for conda but I presume the should/could be a dependency in fabio for h5py and maybe it has previously been there but has been broken?

Any thoughts on this?

Best,
Henning

**Comment by kif** [comment]
Hi Henning

Indeed, we could pull all dependencies, but the list of the is pretty long and some of them require system libraries (hdf5, libjpeg, libtiff, jpeg2000, ...) which cannot easily be installed with "pip" (if at all on certain operating systems). For conda, it is  simpler since conda knows how to install those libraries and is supposed to keep the ecosystem consistent (not a simple task).

This is the reason why we have most dependencies optional with an explicit error message. 

Note that h5py could be not enough: then you will probably need some compression plugins (bitshuffle-LZ4, ...).

**Comment by osholm** [comment]
Thanks for the update Jerome. I will close this issue again then.
