### ISSUE TITLE
The distribution contains everything.

### ISSUE THREAD

**Issue by TLCFEM** [silx-kit/fabio#589]
The distribution package contains many files.
It is effectively an archive of the repository.
Files like tests and CI workflows, repository configurations, and many more, may not be needed in a distribution.

You may want to consider using a `MANIFEST.in` file to strip the distribution down.

See more: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

**Comment by kif** [comment]
Hi Theodore,

Thanks for the feed-back. FabIO is no more using setuptools for some time now and it is true continuous integration scripts and some demo code is laying around. Fortunately, the tests images are not included because they represent 880M, in comparison with the 2.4M of the source code and the 292k of "useless" code.

To my knowledge, meson-python (the tool used for packaging) is not offering a way to exclude a file from packaging.
https://github.com/mesonbuild/meson-python/discussions/567
Suggests to use `.gitattributes` with tag `export-ignore`

Cheers,

Jerome
